export const newsData = [
	{
		title: 'Large heading example',
		date: '2023.07.08',
		desc: 'Elit at felis nullam turpis. Odio amet augue blandit nibh. Euismod enim eget duis adipiscing tortor dui risus viverra sit.',
		tags: ['Porta', 'Mollis', 'Pulvinar'],
		image: '/images/car-3.png'
	},
	{
		title: 'Large heading example',
		date: '2023.07.08',
		desc: 'Elit at felis nullam turpis. Odio amet augue blandit nibh. Euismod enim eget duis adipiscing tortor dui risus viverra sit.',
		tags: ['Porta', 'Mollis', 'Pulvinar'],
		image: '/images/car.png'
	},
	{
		title: 'Large heading example',
		date: '2023.07.08',
		desc: 'Elit at felis nullam turpis. Odio amet augue blandit nibh. Euismod enim eget duis adipiscing tortor dui risus viverra sit.',
		tags: ['Porta', 'Mollis', 'Pulvinar'],
		image: '/images/car.png'
	},
	{
		title: 'Large heading example',
		date: '2023.07.08',
		desc: 'Elit at felis nullam turpis. Odio amet augue blandit nibh. Euismod enim eget duis adipiscing tortor dui risus viverra sit.',
		tags: ['Porta', 'Mollis', 'Pulvinar'],
		image: '/images/car-2.png'
	},
	{
		title: 'Large heading example',
		date: '2023.07.08',
		desc: 'Elit at felis nullam turpis. Odio amet augue blandit nibh. Euismod enim eget duis adipiscing tortor dui risus viverra sit.',
		tags: ['Porta', 'Mollis', 'Pulvinar'],
		image: '/images/merch-bg.png'
	},
	{
		title: 'Large heading example',
		date: '2023.07.08',
		desc: 'Elit at felis nullam turpis. Odio amet augue blandit nibh. Euismod enim eget duis adipiscing tortor dui risus viverra sit.',
		tags: ['Porta', 'Mollis', 'Pulvinar'],
		image: '/images/bg-yt.png'
	}
];

export const serversData = [
	{
		name: 'Faucibus arcu purus feugiat viverra.',
		type: 'Heavy',
		slots_total: 32,
		slots_filled: 31,
		vipSlots_total: 32,
		vipSlots_filled: 31,
		cars_total: 4,
		cars_filled: 2,
		map: 'Shutoko Revival Project',
		region: 'US',
		tier: 3,
		favorite: true,
		ip: '',
		port: ''
	},
	{
		name: 'Vitae molestie pellentesque at',
		type: 'Heavy',
		slots_total: 32,
		slots_filled: 31,
		vipSlots_total: 32,
		vipSlots_filled: 31,
		cars_total: 4,
		cars_filled: 2,
		map: 'Shutoko Revival Project',
		region: 'US',
		tier: 2,
		favorite: false,
		ip: '',
		port: ''
	},
	{
		name: 'Sem dolor integer mattis mattis',
		type: 'Heavy',
		slots_total: 32,
		slots_filled: 31,
		vipSlots_total: 32,
		vipSlots_filled: 31,
		cars_total: 4,
		cars_filled: 2,
		map: 'Shutoko Revival Project',
		region: 'US',
		tier: 3,
		favorite: false,
		ip: '',
		port: ''
	},
	{
		name: 'Adipiscing non feugiat lobortis',
		type: 'Heavy',
		slots_total: 32,
		slots_filled: 31,
		vipSlots_total: 32,
		vipSlots_filled: 31,
		cars_total: 4,
		cars_filled: 2,
		map: 'Shutoko Revival Project',
		region: 'US',
		tier: 2,
		favorite: false,
		ip: '',
		port: ''
	},
	{
		name: 'Arcu lorem vitae etiam ac nec tempor',
		type: 'Heavy',
		slots_total: 32,
		slots_filled: 31,
		vipSlots_total: 32,
		vipSlots_filled: 31,
		cars_total: 4,
		cars_filled: 2,
		map: 'Shutoko Revival Project',
		region: 'US',
		tier: 1,
		favorite: true,
		ip: '',
		port: ''
	},
	{
		name: 'Pretium sed at amet a eros magna',
		type: 'Heavy',
		slots_total: 32,
		slots_filled: 31,
		vipSlots_total: 32,
		vipSlots_filled: 31,
		cars_total: 4,
		cars_filled: 2,
		map: 'Shutoko Revival Project',
		region: 'US',
		tier: 2,
		favorite: false,
		ip: '',
		port: ''
	},
	{
		name: 'Orci massa nulla quis risus. Enim',
		type: 'Heavy',
		slots_total: 32,
		slots_filled: 31,
		vipSlots_total: 32,
		vipSlots_filled: 31,
		cars_total: 4,
		cars_filled: 2,
		map: 'Shutoko Revival Project',
		region: 'US',
		tier: 2,
		favorite: false,
		ip: '',
		port: ''
	},
	{
		name: 'Maecenas habitant ut diam orci sagittis',
		type: 'Heavy',
		slots_total: 32,
		slots_filled: 31,
		vipSlots_total: 32,
		vipSlots_filled: 31,
		cars_total: 4,
		cars_filled: 2,
		map: 'Shutoko Revival Project',
		region: 'US',
		tier: 0,
		favorite: false,
		ip: '',
		port: ''
	},
	{
		name: 'Mauris aenean id lobortis turpis nibh a',
		type: 'Heavy',
		slots_total: 32,
		slots_filled: 31,
		vipSlots_total: 32,
		vipSlots_filled: 31,
		cars_total: 4,
		cars_filled: 2,
		map: 'Shutoko Revival Project',
		region: 'US',
		tier: 0,
		favorite: true,
		ip: '',
		port: ''
	},
	{
		name: 'Commodo dictum fringilla dui proin',
		type: 'Heavy',
		slots_total: 32,
		slots_filled: 31,
		vipSlots_total: 32,
		vipSlots_filled: 31,
		cars_total: 4,
		cars_filled: 2,
		map: 'Shutoko Revival Project',
		region: 'US',
		tier: 2,
		favorite: true,
		ip: '',
		port: ''
	},
	{
		name: 'At euismod aliquam parturient tellus',
		type: 'Heavy',
		slots_total: 32,
		slots_filled: 31,
		vipSlots_total: 32,
		vipSlots_filled: 31,
		cars_total: 4,
		cars_filled: 2,
		map: 'Shutoko Revival Project',
		region: 'US',
		tier: 3,
		favorite: false,
		ip: '',
		port: ''
	}
];

export let friendsData = [
	{
		name: 'happysnake594',
		profilePicture: '/images/ProfileImage.jpeg',
		position: 27,
		tier: 3,
		region: 'eu',
		currentServer: 'Risus pretium'
	},
	{
		name: 'crazyfish228',
		profilePicture: '/images/ProfileImage.jpeg',
		position: 3,
		tier: 3,
		region: 'eu',
		currentServer: 'Tempus nisi sit'
	},
	{
		name: 'silverduck204',
		profilePicture: '/images/ProfileImage.jpeg',
		position: 254,
		tier: 3,
		region: 'eu',
		currentServer: 'Integer lorem'
	},
	{
		name: 'purpleleopard757',
		profilePicture: '/images/ProfileImage.jpeg',
		position: 87,
		tier: 3,
		region: 'eu',
		currentServer: 'Facilisi arcu'
	},
	{
		name: 'ticklishkoala607',
		profilePicture: '/images/ProfileImage.jpeg',
		position: 123,
		tier: 3,
		region: 'eu',
		currentServer: 'Vulputate dui'
	},
	{
		name: 'tinypanda866',
		profilePicture: '/images/ProfileImage.jpeg',
		position: 3,
		tier: 3,
		region: 'eu',
		currentServer: 'Luctus cras'
	},
	{
		name: 'redkoala509',
		profilePicture: '/images/ProfileImage.jpeg',
		position: 645,
		tier: 3,
		region: 'eu',
		currentServer: 'Tellus quis sit'
	}
];

export let userData = {
	username: 'happysnake594',
	region: 'eu',
	dateCreated: '8/16/2017',
	driftPosition: 1,
	cutUpPointsPosition: 324,
	trackPosition: 0,
	tier: 1,
	profilePicture: '/images/ProfileImage.jpeg',
	cover: '/images/profileBg.png',
	fvrtCar: 'Porsche gt3 RS',
	fvrtCarImage: '/images/fvrtCar.png',
	milesDriven: 8644,
	points: 85146375,
	hiddenStats: false
};

export let notifications = [
	{
		type: 'Success',
		unread: true,
		title: 'Netus non tincidunt sit eget nisl nisl orci convallis.',
		desc: 'Sapien egestas aliquam nibh vel at. Nullam malesuada nec bibendum tortor risus volutpat ac.'
	},
	{
		type: 'Info',
		unread: false,
		title: 'Iaculis arcu eu purus mauris tincidunt volutpat.',
		desc: 'Dignissim proin ornare sapien egestas sagittis nulla. Tortor sem ligula enim cursus volutpat.'
	},
	{
		type: 'Success',
		unread: true,
		title: 'Aliquam scelerisque suspendisse proin cursus arcu consectetur nibh tortor.',
		desc: 'Arcu habitasse vestibulum eu in nisi id faucibus. Neque lectus ut euismod fermentum euismod non suspendisse.'
	}
];

export const leaderboardData = [
	{
		position: 1,
		name: 'beautifulbutterfly101',
		image: '/images/ProfileImage.jpeg',
		score: '85.146.375',
		stremid: 'stremid',
		input: 21,
		combo: '10177.8x',
		avg_speed: '174km/h',
		run_time: '1:29:12',
		run_distance: '258.4km',
		car_model: 'Porsche 911 GT3 RS (992',
		server: 'No Hesi Tuned',
		icon: 'NohesiLogo'
	},
	{
		position: 2,
		name: 'speedyrunner202',
		image: '/images/ProfileImage.jpeg',
		score: '82.754.210',
		stremid: 'stremid',
		input: 19,
		combo: '9876.2x',
		avg_speed: '172km/h',
		run_time: '1:32:15',
		run_distance: '245.8km',
		car_model: 'Ferrari 488 GTB',
		server: 'Turbocharged',
		icon: 'TurboLogo'
	},
	{
		position: 3,
		name: 'thunderbolt90',
		image: '/images/ProfileImage.jpeg',
		score: '79.325.678',
		stremid: 'stremid',
		input: 18,
		combo: '9543.6x',
		avg_speed: '169km/h',
		run_time: '1:35:40',
		run_distance: '235.6km',
		car_model: 'Lamborghini Huracan',
		server: 'Supercar',
		icon: 'SupercarLogo'
	},
	{
		position: 4,
		name: 'swiftspeedster55',
		image: '/images/ProfileImage.jpeg',
		score: '100.543.210',
		stremid: 'stremid',
		input: 17,
		combo: '9210.4x',
		avg_speed: '168km/h',
		run_time: '1:38:20',
		run_distance: '225.4km',
		car_model: 'McLaren 720S',
		server: 'High Performance',
		icon: 'McLarenLogo'
	},
	{
		position: 5,
		name: 'driftking2000',
		image: '/images/ProfileImage.jpeg',
		score: '73.215.678',
		stremid: 'stremid',
		input: 16,
		combo: '8987.1x',
		avg_speed: '165km/h',
		run_time: '1:41:05',
		run_distance: '215.2km',
		car_model: 'Nissan Silvia S15',
		server: 'Drift Master',
		icon: 'DriftLogo'
	},
	{
		position: 6,
		name: 'velocityracer88',
		image: '/images/ProfileImage.jpeg',
		score: '70.987.654',
		stremid: 'stremid',
		input: 15,
		combo: '8765.9x',
		avg_speed: '164km/h',
		run_time: '1:43:50',
		run_distance: '205.8km',
		car_model: 'Ford Mustang Shelby GT500',
		server: 'Muscle Beast',
		icon: 'MuscleLogo'
	},
	{
		position: 7,
		name: 'trackstar2000',
		image: '/images/ProfileImage.jpeg',
		score: '68.765.432',
		stremid: 'stremid',
		input: 14,
		combo: '8543.7x',
		avg_speed: '166km/h',
		run_time: '1:46:35',
		run_distance: '195.6km',
		car_model: 'BMW M3',
		server: 'Track Racer',
		icon: 'TrackLogo'
	},
	{
		position: 8,
		name: 'racepro99',
		image: '/images/ProfileImage.jpeg',
		score: '66.543.210',
		stremid: 'stremid',
		input: 13,
		combo: '8321.4x',
		avg_speed: '170km/h',
		run_time: '1:49:20',
		run_distance: '185.4km',
		car_model: 'Audi R8 V10 Plus',
		server: 'German Precision',
		icon: 'AudiLogo'
	},
	{
		position: 9,
		name: 'streetking2001',
		image: '/images/ProfileImage.jpeg',
		score: '64.321.098',
		stremid: 'stremid',
		input: 12,
		combo: '8097.1x',
		avg_speed: '168km/h',
		run_time: '1:52:05',
		run_distance: '175.2km',
		car_model: 'Subaru WRX STI',
		server: 'Street Warrior',
		icon: 'SubaruLogo'
	},
	{
		position: 10,
		name: 'neonracer22',
		image: '/images/ProfileImage.jpeg',
		score: '62.098.765',
		stremid: 'stremid',
		input: 11,
		combo: '7875.6x',
		avg_speed: '167km/h',
		run_time: '1:54:50',
		run_distance: '165.9km',
		car_model: 'Chevrolet Corvette Z06',
		server: 'American Power',
		icon: 'ChevroletLogo'
	},
	{
		position: 11,
		name: 'fastnfurious99',
		image: '/images/ProfileImage.jpeg',
		score: '59.876.543',
		stremid: 'stremid',
		input: 10,
		combo: '7654.3x',
		avg_speed: '165km/h',
		run_time: '1:57:35',
		run_distance: '155.7km',
		car_model: 'Toyota Supra',
		server: 'JDM Legend',
		icon: 'ToyotaLogo'
	},
	{
		position: 12,
		name: 'rallychamp2000',
		image: '/images/ProfileImage.jpeg',
		score: '57.654.321',
		stremid: 'stremid',
		input: 9,
		combo: '7432.9x',
		avg_speed: '163km/h',
		run_time: '2:00:20',
		run_distance: '145.9km',
		car_model: 'Mitsubishi Lancer Evolution',
		server: 'Rally Master',
		icon: 'MitsubishiLogo'
	},
	{
		position: 13,
		name: 'speeddemon2022',
		image: '/images/ProfileImage.jpeg',
		score: '55.432.109',
		stremid: 'stremid',
		input: 8,
		combo: '7210.5x',
		avg_speed: '160km/h',
		run_time: '2:03:05',
		run_distance: '136.2km',
		car_model: 'Honda Civic Type R',
		server: 'Pocket Rocket',
		icon: 'HondaLogo'
	},
	{
		position: 14,
		name: 'thunderstruck99',
		image: '/images/ProfileImage.jpeg',
		score: '53.210.987',
		stremid: 'stremid',
		input: 7,
		combo: '6989.2x',
		avg_speed: '165km/h',
		run_time: '2:05:50',
		run_distance: '126.4km',
		car_model: 'Dodge Challenger SRT Hellcat',
		server: 'Muscle King',
		icon: 'DodgeLogo'
	},
	{
		position: 15,
		name: 'neonrider2002',
		image: '/images/ProfileImage.jpeg',
		score: '50.987.654',
		stremid: 'stremid',
		input: 6,
		combo: '6767.8x',
		avg_speed: '168km/h',
		run_time: '2:08:35',
		run_distance: '116.6km',
		car_model: 'Nissan GT-R',
		server: 'Japanese Beast',
		icon: 'NissanLogo'
	},
	{
		position: 16,
		name: 'racepro2001',
		image: '/images/ProfileImage.jpeg',
		score: '48.765.432',
		stremid: 'stremid',
		input: 5,
		combo: '6546.4x',
		avg_speed: '170km/h',
		run_time: '2:11:20',
		run_distance: '106.8km',
		car_model: 'Chevrolet Camaro ZL1',
		server: 'American Muscle',
		icon: 'ChevroletLogo'
	},
	{
		position: 17,
		name: 'velocityracer2002',
		image: '/images/ProfileImage.jpeg',
		score: '46.543.210',
		stremid: 'stremid',
		input: 4,
		combo: '6324.1x',
		avg_speed: '162km/h',
		run_time: '2:14:05',
		run_distance: '97.1km',
		car_model: 'Ford Focus RS',
		server: 'Hot Hatch',
		icon: 'FordLogo'
	},
	{
		position: 18,
		name: 'silkysmooth22',
		image: '/images/ProfileImage.jpeg',
		score: '44.321.098',
		stremid: 'stremid',
		input: 3,
		combo: '6102.7x',
		avg_speed: '167km/h',
		run_time: '2:16:50',
		run_distance: '87.4km',
		car_model: 'Acura NSX',
		server: 'Luxury Speed',
		icon: 'AcuraLogo'
	},
	{
		position: 19,
		name: 'rallychamp2003',
		image: '/images/ProfileImage.jpeg',
		score: '42.098.765',
		stremid: 'stremid',
		input: 2,
		combo: '5881.3x',
		avg_speed: '160km/h',
		run_time: '2:19:35',
		run_distance: '77.7km',
		car_model: 'Subaru Impreza WRX',
		server: 'Rally Legend',
		icon: 'SubaruLogo'
	},
	{
		position: 20,
		name: 'speedster2003',
		image: '/images/ProfileImage.jpeg',
		score: '39.876.543',
		stremid: 'stremid',
		input: 1,
		combo: '5660.9x',
		avg_speed: '165km/h',
		run_time: '2:22:20',
		run_distance: '68km',
		car_model: 'BMW i8',
		server: 'Futuristic Speed',
		icon: 'BMWiLogo'
	},
	{
		position: 21,
		name: 'turbocharged2000',
		image: '/images/ProfileImage.jpeg',
		score: '37.654.321',
		stremid: 'stremid',
		input: 21,
		combo: '5439.6x',
		avg_speed: '163km/h',
		run_time: '2:25:05',
		run_distance: '58.3km',
		car_model: 'Porsche Cayman GT4',
		server: 'Turbocharged Thrill',
		icon: 'PorscheLogo'
	},
	{
		position: 22,
		name: 'blazingwheels2001',
		image: '/images/ProfileImage.jpeg',
		score: '35.432.109',
		stremid: 'stremid',
		input: 20,
		combo: '5218.2x',
		avg_speed: '166km/h',
		run_time: '2:27:50',
		run_distance: '48.6km',
		car_model: 'Mercedes-Benz AMG GT',
		server: 'Luxury Power',
		icon: 'MercedesLogo'
	},
	{
		position: 23,
		name: 'driftmaster2003',
		image: '/images/ProfileImage.jpeg',
		score: '33.209.876',
		stremid: 'stremid',
		input: 19,
		combo: '4996.9x',
		avg_speed: '168km/h',
		run_time: '2:30:35',
		run_distance: '38.9km',
		car_model: 'Toyota 86',
		server: 'Drift King',
		icon: 'ToyotaLogo'
	},
	{
		position: 24,
		name: 'throttleking2002',
		image: '/images/ProfileImage.jpeg',
		score: '30.987.654',
		stremid: 'stremid',
		input: 18,
		combo: '4775.5x',
		avg_speed: '172km/h',
		run_time: '2:33:20',
		run_distance: '29.2km',
		car_model: 'Audi RS5',
		server: 'German Power',
		icon: 'AudiLogo'
	},
	{
		position: 25,
		name: 'sleekdriver2002',
		image: '/images/ProfileImage.jpeg',
		score: '28.765.432',
		stremid: 'stremid',
		input: 17,
		combo: '4554.1x',
		avg_speed: '170km/h',
		run_time: '2:36:05',
		run_distance: '19.5km',
		car_model: 'Ferrari F8 Tributo',
		server: 'Italian Stallion',
		icon: 'FerrariLogo'
	},
	{
		position: 26,
		name: 'adrenalinejunkie2002',
		image: '/images/ProfileImage.jpeg',
		score: '26.543.210',
		stremid: 'stremid',
		input: 16,
		combo: '4332.7x',
		avg_speed: '173km/h',
		run_time: '2:38:50',
		run_distance: '9.8km',
		car_model: 'Chevrolet Camaro SS',
		server: 'American Power',
		icon: 'ChevroletLogo'
	},
	{
		position: 27,
		name: 'streetracer2002',
		image: '/images/ProfileImage.jpeg',
		score: '24.321.098',
		stremid: 'stremid',
		input: 15,
		combo: '4111.3x',
		avg_speed: '171km/h',
		run_time: '2:41:35',
		run_distance: '0.1km',
		car_model: 'Dodge Charger SRT',
		server: 'Muscle Warrior',
		icon: 'DodgeLogo'
	},
	{
		position: 28,
		name: 'velocityqueen2001',
		image: '/images/ProfileImage.jpeg',
		score: '22.098.876',
		stremid: 'stremid',
		input: 14,
		combo: '3890x',
		avg_speed: '169km/h',
		run_time: '2:44:20',
		run_distance: '10.6km',
		car_model: 'Ford Mustang GT',
		server: 'American Legend',
		icon: 'FordLogo'
	},
	{
		position: 29,
		name: 'trackstar2004',
		image: '/images/ProfileImage.jpeg',
		score: '19.876.543',
		stremid: 'stremid',
		input: 13,
		combo: '3668.6x',
		avg_speed: '175km/h',
		run_time: '2:47:05',
		run_distance: '20.3km',
		car_model: 'Nissan GT-R Nismo',
		server: 'Japanese Power',
		icon: 'NissanLogo'
	},
	{
		position: 30,
		name: 'driftmaster2004',
		image: '/images/ProfileImage.jpeg',
		score: '17.654.321',
		stremid: 'stremid',
		input: 12,
		combo: '3447.2x',
		avg_speed: '173km/h',
		run_time: '2:49:50',
		run_distance: '30km',
		car_model: 'Mazda RX-7',
		server: 'Rotary Master',
		icon: 'MazdaLogo'
	},
	{
		position: 31,
		name: 'supercars2003',
		image: '/images/ProfileImage.jpeg',
		score: '15.432.109',
		stremid: 'stremid',
		input: 11,
		combo: '3225.8x',
		avg_speed: '176km/h',
		run_time: '2:52:35',
		run_distance: '40.6km',
		car_model: 'Lamborghini Aventador SVJ',
		server: 'Italian Power',
		icon: 'LamborghiniLogo'
	},
	{
		position: 32,
		name: 'rallybeast2002',
		image: '/images/ProfileImage.jpeg',
		score: '13.209.876',
		stremid: 'stremid',
		input: 10,
		combo: '3004.4x',
		avg_speed: '172km/h',
		run_time: '2:55:20',
		run_distance: '50.3km',
		car_model: 'Ford Fiesta ST',
		server: 'Rally Warrior',
		icon: 'FordLogo'
	},
	{
		position: 33,
		name: 'speeddemon2004',
		image: '/images/ProfileImage.jpeg',
		score: '10.987.654',
		stremid: 'stremid',
		input: 9,
		combo: '2783x',
		avg_speed: '178km/h',
		run_time: '2:58:05',
		run_distance: '60km',
		car_model: 'Honda S2000',
		server: 'Pocket Rocket',
		icon: 'HondaLogo'
	},
	{
		position: 34,
		name: 'musclecarlover2003',
		image: '/images/ProfileImage.jpeg',
		score: '8.765.432',
		stremid: 'stremid',
		input: 8,
		combo: '2561.6x',
		avg_speed: '174km/h',
		run_time: '3:00:50',
		run_distance: '70.7km',
		car_model: 'Dodge Charger RT',
		server: 'Muscle Madness',
		icon: 'DodgeLogo'
	},
	{
		position: 35,
		name: 'turbocharged2004',
		image: '/images/ProfileImage.jpeg',
		score: '6.543.210',
		stremid: 'stremid',
		input: 7,
		combo: '2340.2x',
		avg_speed: '180km/h',
		run_time: '3:03:35',
		run_distance: '80.4km',
		car_model: 'Porsche 911 Turbo S',
		server: 'Turbocharged Thrill',
		icon: 'PorscheLogo'
	},
	{
		position: 36,
		name: 'hotwheels2003',
		image: '/images/ProfileImage.jpeg',
		score: '4.321.098',
		stremid: 'stremid',
		input: 6,
		combo: '2118.8x',
		avg_speed: '176km/h',
		run_time: '3:06:20',
		run_distance: '90.1km',
		car_model: 'Chevrolet Corvette Stingray',
		server: 'American Power',
		icon: 'ChevroletLogo'
	},
	{
		position: 37,
		name: 'eurospeedster2002',
		image: '/images/ProfileImage.jpeg',
		score: '2.098.876',
		stremid: 'stremid',
		input: 5,
		combo: '1897.4x',
		avg_speed: '182km/h',
		run_time: '3:09:05',
		run_distance: '99.8km',
		car_model: 'BMW M5',
		server: 'German Precision',
		icon: 'BMWiLogo'
	},
	{
		position: 38,
		name: 'japansupercar2004',
		image: '/images/ProfileImage.jpeg',
		score: '765.432',
		stremid: 'stremid',
		input: 4,
		combo: '1676x',
		avg_speed: '178km/h',
		run_time: '3:11:50',
		run_distance: '109.5km',
		car_model: 'Nissan GT-R Nismo',
		server: 'Japanese Power',
		icon: 'NissanLogo'
	},
	{
		position: 39,
		name: 'mustangfanatic2002',
		image: '/images/ProfileImage.jpeg',
		score: '543.210',
		stremid: 'stremid',
		input: 3,
		combo: '1454.6x',
		avg_speed: '184km/h',
		run_time: '3:14:35',
		run_distance: '119.2km',
		car_model: 'Ford Mustang GT350',
		server: 'American Legend',
		icon: 'FordLogo'
	},
	{
		position: 40,
		name: 'supercarlover2003',
		image: '/images/ProfileImage.jpeg',
		score: '321.098',
		stremid: 'stremid',
		input: 2,
		combo: '1233.2x',
		avg_speed: '180km/h',
		run_time: '3:17:20',
		run_distance: '129.9km',
		car_model: 'Ferrari 812 Superfast',
		server: 'Italian Stallion',
		icon: 'FerrariLogo'
	},
	{
		position: 41,
		name: 'hotrod2002',
		image: '/images/ProfileImage.jpeg',
		score: '98.876',
		stremid: 'stremid',
		input: 1,
		combo: '1011.8x',
		avg_speed: '186km/h',
		run_time: '3:20:05',
		run_distance: '139.6km',
		car_model: 'Chevrolet Camaro SS',
		server: 'American Power',
		icon: 'ChevroletLogo'
	},
	{
		position: 42,
		name: 'speeddemon2005',
		image: '/images/ProfileImage.jpeg',
		score: '76.543',
		stremid: 'stremid',
		input: 21,
		combo: '899x',
		avg_speed: '188km/h',
		run_time: '3:22:50',
		run_distance: '149.3km',
		car_model: 'Bugatti Chiron',
		server: 'Hypercar',
		icon: 'BugattiLogo'
	},
	{
		position: 43,
		name: 'supercarlover2004',
		image: '/images/ProfileImage.jpeg',
		score: '54.321',
		stremid: 'stremid',
		input: 20,
		combo: '788.6x',
		avg_speed: '184km/h',
		run_time: '3:25:35',
		run_distance: '159.0km',
		car_model: 'Lamborghini Huracan',
		server: 'Italian Power',
		icon: 'LamborghiniLogo'
	},
	{
		position: 44,
		name: 'trackstar2005',
		image: '/images/ProfileImage.jpeg',
		score: '32.109',
		stremid: 'stremid',
		input: 19,
		combo: '678.2x',
		avg_speed: '190km/h',
		run_time: '3:28:20',
		run_distance: '168.7km',
		car_model: 'McLaren 720S',
		server: 'Track Beast',
		icon: 'McLarenLogo'
	},
	{
		position: 45,
		name: 'driftmaster2005',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 18,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '3:31:05',
		run_distance: '178.4km',
		car_model: 'Toyota Supra Mk4',
		server: 'Drift Legend',
		icon: 'ToyotaLogo'
	},
	{
		position: 46,
		name: 'throttleking2003',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 17,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '3:33:50',
		run_distance: '188.1km',
		car_model: 'Audi RS6',
		server: 'German Muscle',
		icon: 'AudiLogo'
	},
	{
		position: 47,
		name: 'eurospeedster2003',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 16,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '3:36:35',
		run_distance: '197.8km',
		car_model: 'BMW M3',
		server: 'European Speed',
		icon: 'BMWiLogo'
	},
	{
		position: 48,
		name: 'sleekdriver2003',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 15,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '3:39:20',
		run_distance: '207.5km',
		car_model: 'Ferrari 458 Italia',
		server: 'Italian Speed',
		icon: 'FerrariLogo'
	},
	{
		position: 49,
		name: 'musclecarlover2004',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 14,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '3:42:05',
		run_distance: '217.2km',
		car_model: 'Ford Mustang Shelby GT350',
		server: 'American Muscle',
		icon: 'FordLogo'
	},
	{
		position: 50,
		name: 'speeddemon2006',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 13,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '3:44:50',
		run_distance: '226.9km',
		car_model: 'Dodge Challenger SRT Demon',
		server: 'Muscle Power',
		icon: 'DodgeLogo'
	},
	{
		position: 51,
		name: 'supercarlover2005',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 12,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '3:47:35',
		run_distance: '236.6km',
		car_model: 'Lamborghini Gallardo',
		server: 'Italian Exotic',
		icon: 'LamborghiniLogo'
	},
	{
		position: 52,
		name: 'trackstar2006',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 11,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '3:50:20',
		run_distance: '246.3km',
		car_model: 'Porsche 911 GT3',
		server: 'Track Monster',
		icon: 'PorscheLogo'
	},
	{
		position: 53,
		name: 'driftmaster2006',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 10,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '3:53:05',
		run_distance: '256km',
		car_model: 'Nissan 350Z',
		server: 'Drift King',
		icon: 'NissanLogo'
	},
	{
		position: 54,
		name: 'throttleking2004',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 9,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '3:55:50',
		run_distance: '265.7km',
		car_model: 'BMW M4',
		server: 'German Muscle',
		icon: 'BMWiLogo'
	},
	{
		position: 55,
		name: 'sleekdriver2004',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 8,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '3:58:35',
		run_distance: '275.4km',
		car_model: 'Ferrari California',
		server: 'Italian Speedster',
		icon: 'FerrariLogo'
	},
	{
		position: 56,
		name: 'musclecarlover2005',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 7,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:01:20',
		run_distance: '285.1km',
		car_model: 'Chevrolet Camaro Z28',
		server: 'American Muscle',
		icon: 'ChevroletLogo'
	},
	{
		position: 57,
		name: 'speeddemon2007',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 6,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:04:05',
		run_distance: '294.8km',
		car_model: 'Dodge Viper',
		server: 'Muscle Power',
		icon: 'DodgeLogo'
	},
	{
		position: 58,
		name: 'supercarlover2006',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 5,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:06:50',
		run_distance: '304.5km',
		car_model: 'Ferrari F430',
		server: 'Italian Stallion',
		icon: 'FerrariLogo'
	},
	{
		position: 59,
		name: 'trackstar2007',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 4,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:09:35',
		run_distance: '314.2km',
		car_model: 'Lamborghini Murcielago',
		server: 'Track Champion',
		icon: 'LamborghiniLogo'
	},
	{
		position: 60,
		name: 'driftmaster2007',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 3,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:12:20',
		run_distance: '323.9km',
		car_model: 'Mazda RX-8',
		server: 'Drift Master',
		icon: 'MazdaLogo'
	},
	{
		position: 61,
		name: 'throttleking2005',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 2,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:15:05',
		run_distance: '333.6km',
		car_model: 'Mercedes-Benz C63 AMG',
		server: 'German Muscle',
		icon: 'MercedesLogo'
	},
	{
		position: 62,
		name: 'sleekdriver2005',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 1,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:17:50',
		run_distance: '343.3km',
		car_model: 'Aston Martin Vantage',
		server: 'British Elegance',
		icon: 'AstonMartinLogo'
	},
	{
		position: 63,
		name: 'rallybeast2004',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 21,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:20:35',
		run_distance: '353km',
		car_model: 'Subaru WRX STI',
		server: 'Rally Warrior',
		icon: 'SubaruLogo'
	},
	{
		position: 64,
		name: 'speedster2005',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 20,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:23:20',
		run_distance: '362.7km',
		car_model: 'Chevrolet Corvette Z06',
		server: 'American Muscle',
		icon: 'ChevroletLogo'
	},
	{
		position: 65,
		name: 'velocityracer2004',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 19,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:26:05',
		run_distance: '372.4km',
		car_model: 'Ford Mustang EcoBoost',
		server: 'American Legend',
		icon: 'FordLogo'
	},
	{
		position: 66,
		name: 'turbocharged2006',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 18,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:28:50',
		run_distance: '382.1km',
		car_model: 'Nissan 370Z',
		server: 'Turbocharged Thrill',
		icon: 'NissanLogo'
	},
	{
		position: 67,
		name: 'hotwheels2004',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 17,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:31:35',
		run_distance: '391.8km',
		car_model: 'Dodge Challenger Hellcat',
		server: 'Muscle Madness',
		icon: 'DodgeLogo'
	},
	{
		position: 68,
		name: 'eurospeedster2004',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 16,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:34:20',
		run_distance: '401.5km',
		car_model: 'Audi S5',
		server: 'European Speed',
		icon: 'AudiLogo'
	},
	{
		position: 69,
		name: 'driftmaster2008',
		image: '/images/ProfileImage.jpeg',
		score: '9.876',
		stremid: 'stremid',
		input: 15,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:37:05',
		run_distance: '411.2km',
		car_model: 'Toyota AE86',
		server: 'Drift King',
		icon: 'ToyotaLogo'
	},
	{
		position: 70,
		name: 'supercarlover2007',
		image: '/images/ProfileImage.jpeg',
		score: 9.876,
		stremid: 'stremid',
		input: 14,
		combo: '567.8x',
		avg_speed: '186km/h',
		run_time: '4:39:50',
		run_distance: '420.9km',
		car_model: 'Porsche 911 Carrera S',
		server: 'German Precision',
		icon: 'PorscheLogo'
	}
];


